services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${COMPOSE_PROJECT_NAME}
    image: druidfi/drupal-web:v8.3.8
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:delegated
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DRUSH_OPTIONS_URI: https://${DRUPAL_HOSTNAME}
      SIMPLETEST_BASE_URL: http://app:8080
      SIMPLETEST_DB: mysql://drupal:drupal@db:3306/drupal
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-false}
      WEBROOT: web
      # This is for Starshot installer
      DB: mysql://drupal:drupal@db:3306/drupal
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080
      - traefik.docker.network=stonehenge-network
    networks:
      - default
      - stonehenge-network

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: druidfi/mysql:8.0-drupal-lts
    ports:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pdrupal" ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  stonehenge-network:
    external: true
